name: ⚖️ Add Case to Existing EO
description: Report a court case or other relevant case that should be added to an existing Executive Order
labels: [case-addition]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us track cases related to Executive Orders! Please provide information about the case you'd like to add.
  - type: input
    id: eo-number
    attributes:
      label: Executive Order Number
      description: The number of the Executive Order this case relates to
      placeholder: e.g., 14100
    validations:
      required: true
  - type: input
    id: case-name
    attributes:
      label: Case Name
      description: The official name of the case
      placeholder: e.g., State of Washington v. Trump
    validations:
      required: true
  - type: input
    id: case-url
    attributes:
      label: Case URL
      description: Link to the official court filing, opinion, or a reliable source about the case
      placeholder: https://www.courts.gov/...
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional context or information about this case
      placeholder: Add any other relevant details here
    validations:
      required: false
