name: 📝 Missing Executive Order
description: Report a missing Executive Order in the tracker
labels: [missing-content]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us keep the Executive Orders Tracker complete! Please provide information about the missing Executive Order.
  - type: input
    id: eo-number
    attributes:
      label: Executive Order Number
      description: The official number of the Executive Order
      placeholder: e.g., 14100
    validations:
      required: true
  - type: input
    id: eo-date
    attributes:
      label: Date Signed
      description: The date the Executive Order was signed
      placeholder: YYYY-MM-DD
    validations:
      required: true
  - type: input
    id: eo-title
    attributes:
      label: Executive Order Title
      description: The official title of the Executive Order
      placeholder: e.g., Executive Order on Preventing and Combating Discrimination on the Basis of Gender Identity or Sexual Orientation
    validations:
      required: true
  - type: input
    id: eo-url
    attributes:
      label: Official URL
      description: Link to the Executive Order on the White House website or Federal Register
      placeholder: https://www.whitehouse.gov/briefing-room/presidential-actions/...
    validations:
      required: true
  - type: textarea
    id: additional-info
    attributes:
      label: Additional Information
      description: Any additional context or information about this Executive Order
      placeholder: Add any other relevant information here
    validations:
      required: false