name: Add Case

on:
  issues:
    types: [opened, labeled]

jobs:
  add-case:
    if: contains(github.event.issue.labels.*.name, 'case-addition')
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Get issue form data
        id: get-issue-data
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body;
            const lines = body.split('\n');
            const data = {};

            for (let i = 0; i < lines.length; i++) {
              const line = lines[i];
              if (line.includes('### Executive Order Number') && i + 1 < lines.length) {
                data.eoNumber = lines[i + 1].trim();
              }
              if (line.includes('### Case Name') && i + 1 < lines.length) {
                data.caseName = lines[i + 1].trim();
              }
              if (line.includes('### Case URL') && i + 1 < lines.length) {
                data.caseUrl = lines[i + 1].trim();
              }
            }

            if (!data.caseUrl) {
              core.setFailed('Case URL is required');
              return;
            }

            core.setOutput('eo-number', data.eoNumber);
            core.setOutput('case-name', data.caseName);
            core.setOutput('case-url', data.caseUrl);

            // For debugging
            console.log('Extracted data:', data);

      - name: Update data.json
        id: update-data
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const eoNumber = '${{ steps.get-issue-data.outputs.eo-number }}';
            const caseName = '${{ steps.get-issue-data.outputs.case-name }}';
            const caseUrl = '${{ steps.get-issue-data.outputs.case-url }}';

            const data = JSON.parse(fs.readFileSync('src/data.json', 'utf8'));

            const eo = data.find(item => item.id === eoNumber);
            if (!eo) {
              core.setFailed(`Executive Order ${eoNumber} not found`);
              return;
            }

            if (!eo.challenges) {
              eo.challenges = [];
            }

            eo.challenges.push({
              title: caseName,
              url: caseUrl
            });

            if (eo.status === 'enacted') {
              eo.status = 'challenged';
            }

            fs.writeFileSync('src/data.json', JSON.stringify(data, null, 2));

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "Add case ${{ steps.get-issue-data.outputs.case-name }} to EO ${{ steps.get-issue-data.outputs.eo-number }}"
          title: "Add case ${{ steps.get-issue-data.outputs.case-name }} to EO ${{ steps.get-issue-data.outputs.eo-number }}"
          body: |
            Adds new case from issue #${{ github.event.issue.number }}

            Case Name: ${{ steps.get-issue-data.outputs.case-name }}
            Case URL: ${{ steps.get-issue-data.outputs.case-url }}
            EO Number: ${{ steps.get-issue-data.outputs.eo-number }}
          branch: add-case/${{ github.event.issue.number }}
