name: Trigger CL update on PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  run-on-case-addition:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'case-addition')
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
        actions: write
    steps:
      - name: Trigger daily-cl workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'daily-cl.yml',
              ref: 'main'
            });
