name: Trigger CL update on PR merge

on:
  pull_request:
    types:
      - closed

jobs:
  run-on-case-addition:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'case-addition')
    runs-on: ubuntu-latest
    permissions:
        contents: write
        issues: write
        pull-requests: write
        actions: write
    steps:
      - name: Extract document ID from PR body
        id: extract-id
        uses: actions/github-script@v7
        with:
          script: |
            const prBody = context.payload.pull_request.body;
            const urlMatch = prBody.match(/Case URL: .*courtlistener\.com\/docket\/(\d+)(\/|$)/i);
            if (urlMatch) {
              core.setOutput('documentId', urlMatch[1]);
            }

      - name: Trigger daily-cl workflow
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const inputs = '${{ steps.extract-id.outputs.documentId }}'
              ? { documentId: '${{ steps.extract-id.outputs.documentId }}' }
              : {};
            
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'daily-cl.yml',
              ref: 'main',
              inputs: inputs
            });
