name: Daily Court Listener Update

on:
  schedule:
    # Run at 8:10 AM Pacific (15:10 UTC)
    - cron: "10 15 * * *"
  workflow_dispatch:
    inputs:
      documentId:
        description: 'Specific Court Listener document ID to update'
        required: false
        type: string

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  update:
    runs-on: ubuntu-latest
    env:
      CL_API_KEY: ${{ secrets.CL_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run update script
        run: |
          if [ -n "${{ inputs.documentId }}" ]; then
            python scripts/cl_updater.py "${{ inputs.documentId }}"
          else
            python scripts/cl_updater.py
          fi

      - name: 🤔 Check for changes
        id: changes
        run: |
          if [[ -n "$(git status --porcelain src/data.json)" ]]; then
            echo "changed=1" >> $GITHUB_OUTPUT
            echo "Changes detected in src/data.json"
          else
            echo "changed=0" >> $GITHUB_OUTPUT
            echo "No changes detected in src/data.json"
          fi

      - name: Create Pull Request if changes
        if: steps.changes.outputs.changed == '1'
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: "chore: update Court Listener data"
          title: "Update Court Listener Data"
          body: |
            Automated update from Court Listener data source.

            This PR was automatically created by the daily update workflow.
          branch: automated-cl-update
          delete-branch: true
